[package]
name = "nshogi"
version = "0.1.2"
edition = "2024"

[build-dependencies]
cc = { version = "1.2.26", features = ["parallel"] }

[profile.test]
inherits = "release"

[features]
sse41 = []
sse42 = ["sse41"]
avx   = ["sse42"]
avx2  = ["avx"]
neon  = []
